export const prds = [
  {
    slug: 'ltv',
    title: 'LTV Report',
    summary: 'PRD and interactive mock for the Lifetime Value report — cohort segmentation, revenue retention, churn proxies, and operator-level LTV breakdowns.',
    reportSlug: 'ltv',
    status: 'Draft',
    published: true,
    prdUrl: '/prd/prd_ltv-report.html',
    mockUrl: '/prd/prd_mock_ltv-report.html',
    author: 'david.jung@bondsports.co',
    updatedAt: '2026-05-19',
  },
  {
    slug: 'credits-and-debits',
    title: 'Credits & Debits Report',
    summary: 'Finance-facing GL journal entry export. Pushes recognized credits and debits directly into Bond\'s ERP — replaces the manual quarterly Excel reconciliation.',
    reportSlug: 'credits-and-debits',
    status: 'Draft',
    published: true,
    prdUrl: null,
    mockUrl: '/prd/prd_mock_credits-and-debits.html',
    author: 'david.jung@bondsports.co',
    updatedAt: '2026-04-28',
  },
  {
    slug: 'utilization',
    title: 'Utilization Report',
    summary: 'PRD and interactive Sigma mock for the facility utilization report. Covers prime/non-prime segmentation, opportunity cost, and operator-configurable prime hours.',
    reportSlug: 'utilization',
    status: 'Draft',
    published: false,
    prdUrl: '/prd/prd_utilization_report.html',
    mockUrl: '/prd/prd_mock_utilization-report.html',
    author: 'david.jung@bondsports.co',
    updatedAt: '2026-04-24',
  },
]
