export const changelog = [
  {
    date: '2026-05-20',
    title: 'Data Share & Export — cost analysis',
    description: 'Quantified Snowflake compute + storage cost of customer-facing data shares and ad-hoc CSV exports. Identified the top three orgs driving share cost and the break-even threshold for moving them to a dedicated report.',
    project: 'Data Warehouse',
    published: true,
  },
  {
    date: '2026-05-19',
    title: 'LTV Report — PRD finalized',
    description: 'Full PRD and interactive Sigma mock for the Lifetime Value report. Covers cohort segmentation, revenue retention, churn proxies, and operator-level LTV breakdowns. Ready for build review with Brett.',
    project: 'LTV Report',
    published: true,
  },
  {
    date: '2026-05-19',
    title: 'Reporting Triage — silent token refresh + reconnect banner',
    description: 'Eliminated the hourly re-login problem. OAuth refresh tokens now persist; expired access tokens are silently renewed in the background. When refresh truly fails, a prominent red banner with a one-click "Reconnect Gmail" button replaces the old behavior of hidden settings-panel flags.',
    project: 'Reporting Triage',
    published: true,
  },
  {
    date: '2026-05-18',
    title: 'Reporting Triage — multi-user hardening',
    description: 'Server-side deduplication of cross-user issues, partial unique index in Supabase, switch to merge-on-conflict for auto-resolutions, and visible surfacing of Haiku failures. Closed the top four criticals from a full-project code review.',
    project: 'Reporting Triage',
    published: true,
  },
  {
    date: '2026-05-08',
    title: 'Sigma ↔ Cognito SSO — walkthrough complete',
    description: 'Phase-1 walkthrough of federating Bond\'s AWS Cognito identity into Sigma via SAML, with Ankita Dalvi from Sigma. David owns the configuration; this unblocks embedded analytics across the product.',
    project: 'Sigma Embed',
    published: false,
  },
  {
    date: '2026-05-08',
    title: 'Bond Analytics ERD — refreshed (light mode)',
    description: 'Updated entity-relationship diagram of the analytics warehouse — Bond-styled, light mode, with all the production fact and dimension tables Brett maintains in dbt.',
    project: 'Analytics Architecture',
    published: true,
  },
  {
    date: '2026-05-07',
    title: 'Bond Analytics — architecture overview',
    description: 'End-to-end architecture diagram of the data stack: app DB → Snowflake → dbt → Sigma → embedded reports and triage tooling. Now the canonical reference when new team members or stakeholders ask "how does Bond analytics work?"',
    project: 'Analytics Architecture',
    published: true,
  },
  {
    date: '2026-05-07',
    title: 'Competitor Reporting — knowledge base',
    description: 'Synthesized competitor intel on how peer SaaS players in sports/facilities deliver embedded reporting to operators. Informs the Sigma embed roadmap and PRD priorities.',
    project: 'Competitive',
    published: false,
  },
  {
    date: '2026-05-07',
    title: 'AI-pair-coding sessions — retrospective',
    description: 'Catalogued AI-pair-coding sessions across the analytics tools (Triage, Sigma Admin, R&A Roadmap, Analytics Hub). What worked, what didn\'t, and the patterns we\'re standardizing on going forward.',
    project: 'Analytics Hub',
    published: false,
  },
  {
    date: '2026-05-06',
    title: 'Snowflake MCP — setup playbook',
    description: 'Documented the Snowflake-via-MCP setup so the data team can query the warehouse directly from Claude during issue triage and exploratory analysis. Materially speeds up "is this a one-off or a pattern?" investigations.',
    project: 'Tooling',
    published: true,
  },
  {
    date: '2026-05-04',
    title: 'Bond accounting methodology — AR aging architecture',
    description: 'Documented the two-pipeline AR aging architecture (Cash/Defer-on-Invoice via payment_line_items; Defer-on-Payment via Actions with FIFO). Establishes the reliable methodology for revenue recognition questions.',
    project: 'Financial Reporting',
    published: true,
  },
  {
    date: '2026-04-28',
    title: 'Credits & Debits Report — PRD complete',
    description: 'Full PRD for the finance-facing GL journal entry export, designed to push recognized credits and debits directly into Bond\'s ERP. Replaces the manual quarterly Excel reconciliation.',
    project: 'Credits & Debits Report',
    published: true,
  },
  {
    date: '2026-04-24',
    title: 'Bond Analytics Hub launched',
    description: 'Central portal for the Data & Analytics team — tools directory, PRDs, reports library, playbooks, and changelog.',
    project: 'Analytics Hub',
    published: true,
  },
  {
    date: '2026-04-24',
    title: 'Utilization Report — PRD + interactive mock complete',
    description: 'Full PRD document and Sigma-style interactive HTML mock for the Utilization Report. Covers facility utilization %, opportunity cost, prime/non-prime segmentation, and a heatmap visualization.',
    project: 'Utilization Report',
    published: false,
  },
  {
    date: '2026-04-10',
    title: 'Reporting Triage — auth & Gmail link fixes',
    description: 'Fixed Bond email bleed-through in triage results, eliminated double OAuth login prompt, and fixed Gmail links for teammates who weren\'t the original syncing user.',
    project: 'Reporting Triage',
    published: true,
  },
  {
    date: '2026-04-08',
    title: 'Reporting Triage — reliability and triage quality improvements',
    description: 'Switched to per-email individual triage (eliminates batch misses), added Supabase merge-on-sync to prevent lost issues, and added a live Jira status badge to each card.',
    project: 'Reporting Triage',
    published: true,
  },
  {
    date: '2026-04-07',
    title: 'Reporting Triage — Slack integration and smart auto-resolution',
    description: 'New sync notifications post to #analytics-email-monitor. Scheduled M-F 9am daily summary. Haiku now classifies Bond replies as RESOLVED vs ACKNOWLEDGEMENT — CS quick replies no longer falsely close tickets.',
    project: 'Reporting Triage',
    published: true,
  },
  {
    date: '2026-04-06',
    title: 'Reporting Triage — initial launch',
    description: 'Gmail-connected triage dashboard goes live. AI classification of data issues, temperature ratings, Jira search and create, Supabase persistence, multi-user support.',
    project: 'Reporting Triage',
    published: true,
  },
]
