export const tools = [
  {
    id: 'triage',
    name: 'Reporting Triage',
    description: 'AI-triaged inbound data issues from the customer success inbox. Surfaces data engineering tickets with temperature ratings and Jira integration.',
    url: 'https://fantastic-praline-b55509.netlify.app',
    internalPath: '/triage',
    host: 'Netlify',
    owner: 'david.jung@bondsports.co',
    category: 'Internal Apps',
    published: true,
  },
  {
    id: 'sigma-admin',
    name: 'Sigma Admin',
    description: 'Internal CS tool for managing Sigma Computing users — provisioning, directory browsing, and email broadcast to workbook members.',
    url: 'https://sigma-admin-nu.vercel.app',
    host: 'Vercel',
    owner: 'david.jung@bondsports.co',
    category: 'Internal Apps',
    published: true,
  },
  {
    id: 'roadmap',
    name: 'R&A Roadmap',
    description: 'Leadership-facing roadmap dashboard for the Reporting & Analytics domain. Tracks initiatives, status, and timeline.',
    url: 'https://raroadmap.netlify.app',
    host: 'Netlify',
    owner: 'david.jung@bondsports.co',
    category: 'Internal Apps',
    published: true,
  },
  {
    id: 'analytics-hub',
    name: 'Bond Analytics Hub',
    description: 'This portal — central directory of Data & Analytics tools, reports, PRDs, knowledge base articles, and shipping analytics.',
    url: 'https://bond-analytics-hub.netlify.app',
    host: 'Netlify',
    owner: 'david.jung@bondsports.co',
    category: 'Internal Apps',
    published: true,
  },
  {
    id: 'sigma',
    name: 'Sigma',
    description: 'Bond\'s primary BI and reporting workspace. Live dashboards, workbooks, and ad-hoc analysis for operators and internal teams.',
    url: 'https://app.sigmacomputing.com/bond-sports',
    host: 'Sigma Computing',
    owner: 'Data team',
    category: 'BI & Reporting',
    published: true,
  },
  {
    id: 'snowflake',
    name: 'Snowflake',
    description: 'Bond\'s cloud data warehouse. Source of truth for all analytics data, dbt models, and report workloads.',
    url: 'https://app.snowflake.com',
    host: 'Snowflake',
    owner: 'brett@bondsports.co',
    category: 'Data Warehouse',
    published: true,
  },
  {
    id: 'jira',
    name: 'Jira',
    description: 'Issue tracking for REP and SB projects. Data engineering tickets, sprint planning, and incident management.',
    url: 'https://bondsports.atlassian.net',
    host: 'Atlassian',
    owner: 'Data team',
    category: 'Project Management',
    published: true,
  },
  {
    id: 'dbt-cloud',
    name: 'dbt Cloud',
    description: 'Transformation layer on top of Snowflake. 280+ SQL models maintained by Brett — source of all warehouse marts and dimensions.',
    url: 'https://cloud.getdbt.com',
    host: 'dbt Labs',
    owner: 'brett@bondsports.co',
    category: 'Data Warehouse',
    published: true,
  },
]

export const TOOL_CATEGORIES = ['Internal Apps', 'BI & Reporting', 'Data Warehouse', 'Project Management']
